# Generated by Django 3.2.9 on 2021-12-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employers',
            name='age',
            field=models.IntegerField(verbose_name='возраст'),
        ),
    ]
