# Generated by Django 3.2.9 on 2021-12-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employers_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='floor',
            field=models.IntegerField(verbose_name='Этаж'),
        ),
    ]
