# Generated by Django 3.2.9 on 2021-12-03 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_department_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='employers',
            name='programming_lan',
            field=models.ForeignKey(default=56, on_delete=django.db.models.deletion.CASCADE, related_name='programming', to='employee.programminglanguage', verbose_name='Язык программирования'),
            preserve_default=False,
        ),
    ]
